///------------------------------------------------------///
/// Author:     Stig Halfdan Juhl Turner
/// E-mail:     sttur14@student.sdu.dk
/// Date:       25/02/2016
/// Copyright:  None
///
/// Description:
/// Class for loading camera calibration file(.yaml)
/// generated by ROS indigos(www.ros.org) camera_calibration
/// package to use with OpenCV(opencv.org).
/// Please note minor changes must be made to
/// the .yaml file for this class to work.
///
/// Changes needed:
/// 1. Add a new line with "%YAML:1.0" at start of file
/// 2. Add "!!opencv-matrix" behind all matrix name
///     declarations (camera_matrix,
///     distortion_coefficients, rectification_matrix
///     and projection_matrix).
/// 3. After each line with "  cols:" declarations a
///     new line with "  dt: d" must be added.
///
/// Example:
/// Original camera_matrix:
///      camera_matrix:
///        rows: 3
///        cols: 3
///        data: [...]
/// Is changed to:
///     camera_matrix: !!opencv-matrix
///       rows: 3
///       cols: 3
///       dt: d
///       data: [...]
///------------------------------------------------------///

#include <opencv2/opencv.hpp>
using namespace std;

class CalibrationData{
public:
    CalibrationData(string _filePath);
    void printCalibrationData();
    int width, height;
    std::string camera_name;
    cv::Mat camera_matrix;
    string distortion_model;
    cv::Mat distortion_coff;
    cv::Mat rectification_matrix;
    cv::Mat projection_matrix;
};
